#!/bin/bash
if pidof -o %PPID -x "$(basename $0)"; then
  exit 1
fi


# Change parameters below:
UNIONFSRWPATH='/media/data/' # unionfs-fuse RW directory
RCLONEDEST='gdrive_decrypted:' # rclone destination
MINAGE=1 # minimum age (in minutes)


# Do not change anything below!
LOGFILE="/var/log/$(basename ${0%.*}).log"
RCLONEDEST="${RCLONEDEST%/}/"
RCLONEREMOTE="${RCLONEDEST%%/*}"
RCLONEREMOTEPATH="/${RCLONEDEST#*/}"
RCLONEREMOTENICE="${RCLONEREMOTE%%:*}"
UNIONFSRWPATH="${UNIONFSRWPATH%/}"
UNIONFSMETADIR=".unionfs"
UNIONFSMETAPATH="$UNIONFSRWPATH/$UNIONFSMETADIR"
UNIONFSMETAHIDDEN="_HIDDEN~"
DELETED=false



# SYNC UNIONFS METADATA WITH RCLONE RESTINATION
# Remove folders
while IFS= read -r -d '' FOLDER; do
  # Build path to delete  
  RCLONEDELETEFOLDER="$RCLONEREMOTE$RCLONEREMOTEPATH${FOLDER#*$UNIONFSMETAPATH/}"
  RCLONEDELETEFOLDER="${RCLONEDELETEFOLDER%$UNIONFSMETAHIDDEN}"
  UNIONFSDELETEFOLDER1="$FOLDER"
  UNIONFSDELETEFOLDER2="${FOLDER%$UNIONFSMETAHIDDEN}"
  RAWDELETEFOLDER="${FOLDER#*$UNIONFSMETAPATH/}"
  RAWDELETEFOLDER="/${RAWDELETEFOLDER%$UNIONFSMETAHIDDEN}"
   
  #Delete on rclone destination
  echo "$(date "+%Y/%m/%d %T") Deleting directory on $RCLONEREMOTENICE: $RAWDELETEFOLDER" | tee -a $LOGFILE
  rclone purge "$RCLONEDELETEFOLDER" 2>&1 | tee -a $LOGFILE

  # Delete on unionfs
  rm -r "$UNIONFSDELETEFOLDER1"
  if [ -d "$UNIONFSDELETEFOLDER2" ]; then
    rm -r "$UNIONFSDELETEFOLDER2"
  fi
done < <(find $UNIONFSMETAPATH -depth -type d -mmin +$MINAGE -name *$UNIONFSMETAHIDDEN -print0)

# Remove files
while IFS= read -r -d '' FILE; do
  # Build path to delete
  RCLONEDELETEFILE="$RCLONEREMOTE$RCLONEREMOTEPATH${FILE#*$UNIONFSMETAPATH/}"
  RCLONEDELETEFILE="${RCLONEDELETEFILE%$UNIONFSMETAHIDDEN}"
  UNIONFSDELETEFILE="$FILE"
  RAWDELETEFILE="${FILE#*$UNIONFSMETAPATH}"
  RAWDELETEFILE="${RAWDELETEFILE%$UNIONFSMETAHIDDEN}"

  # Delete on rclone destination
  echo "$(date "+%Y/%m/%d %T") Deleting file on $RCLONEREMOTENICE: $RAWDELETEFILE" | tee -a $LOGFILE
  rclone delete "$RCLONEDELETEFILE" 2>&1 | tee -a $LOGFILE

  # Delete on unionfs
  rm -r "$UNIONFSDELETEFILE"
done < <(find $UNIONFSMETAPATH -type f -mmin +$MINAGE -name *$UNIONFSMETAHIDDEN -print0)


# MOVE FILES FROM UNIONFS RW DIRECTORY TO RCLONE DESTINATION
if [ -n "$(find $UNIONFSRWPATH -type f ! -path "$UNIONFSMETAPATH*" -mmin +$MINAGE)" ]; then
  echo "$(date "+%Y/%m/%d %T") Upload to $RCLONEREMOTENICE started" | tee -a $LOGFILE
  rclone move $UNIONFSRWPATH/ $RCLONEREMOTE$RCLONEREMOTEPATH/ --verbose --checksum --no-traverse --transfers=30 --checkers=30 --delete-after --min-age "$MINAGE"m --exclude "$UNIONFSMETADIR**" 2>&1 | tee -a $LOGFILE
  echo "$(date "+%Y/%m/%d %T") Upload to $RCLONEREMOTENICE finished" | tee -a $LOGFILE
fi

# Cleaning up unionfs RW directory
if [ -n "$(find $UNIONFSRWPATH -depth -mindepth 1 -type d -not -path "$UNIONFSMETAPATH/*" -mmin +$MINAGE -empty)" ]; then
  echo "$(date "+%Y/%m/%d %T") Cleaning up unionfs RW directory" | tee -a $LOGFILE
  find $UNIONFSRWPATH -depth -mindepth 1 -type d -not -path "$UNIONFSMETAPATH/*" -mmin +$MINAGE -empty -exec rm -r {} \;
fi


exit
